name: chatapploydlab
description: Chat Application example.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Firebase Packages
  firebase_core: 1.2.1
  cloud_firestore: ^2.2.1
  firebase_storage: ^8.1.1
  firebase_auth: ^1.3.0

  #Notification Pacakges
  firebase_messaging: ^10.0.1
  flutter_local_notifications: ^6.0.0
  flutter_app_badger: ^1.2.0

  #Image pick from library, crop image after pick image.
  image_picker: ^0.8.0+3
  image_cropper: ^1.4.0
  cached_network_image: ^3.0.0-nullsafety
  photo_view: ^0.11.1
  font_awesome_flutter: ^9.0.0-nullsafety


  #ETC
  shared_preferences: ^2.0.4
  url_launcher: ^6.0.2
  intl: ^0.17.0

  #Agora Integrations
  agora_rtc_engine: ^4.0.2
  permission_handler: 8.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/youtube_screenshot.png